version: "3.9"

services:
  api:
    build: .
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=gmtii
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/data

  celery:
    build: .
    command: celery -A config worker --loglevel=INFO
    depends_on:
      - db
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13.4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672 # RabbitMQ management interface

  tests:
    build: .
    command: ./wait-for-it.sh db:5432 -- ptw
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
