# Generated by Django 4.1.2 on 2024-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_publisher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
