# Generated by Django 4.1.2 on 2024-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_video_video_file_alter_video_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("video", models.FileField(upload_to="blog/videos")),
                ("categories", models.ManyToManyField(to="blog.category")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
