# Generated by Django 4.1.2 on 2024-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_content_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="categories",
            field=models.ManyToManyField(related_name="contents", to="blog.category"),
        ),
    ]
